/*************************************************************
@Name: APTS_CopyDataWrapper
@Author: Hardik Shah,Nishi Kushwaha
@CreateDate: 03 November 2015
@Description: Wrapper Class for APTS_CopyStagingData
@UsedBy: APTS_CopyStagingData.cls
******************************************************************/

public class APTS_CopyDataWrapper {
    
    public String sErrorMessage = '';
    public boolean bIsUpsertFail = false;
    

}